#!/bin/sh
:; exec gosh -r7 -- $0 "$@"

(import (scheme base)
        (scheme process-context)
        (piru cli))

(define (main args)
  (run args))

(main (command-line))

;; Local Variables:
;; mode: scheme
;; End:
